version: 2.1

commands: 
  install-vault:
    steps:
      - run:
          name: Install Vault
          command: |
            vault -h && exit 0 || echo "Installing vault..."
            # only runs if vault command above fails
            echo "Update, install gpg..."
            sudo apt update && sudo apt install gpg
            echo "Do gpg stuff..."
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
            gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            echo "Update, install Vault..."
            sudo apt update && sudo apt install vault

  vault-auto-auth:
    description: "Use Vault auto auth to load secrets"
    steps:
      - run:
          name: Auto-authenticate with Vault
          command: |
            # Write the CircleCI provided value to a file read by Vault
            echo $CIRCLE_OIDC_TOKEN > .circleci/vault/token.json
            # Substitute the env vars in our context to render the Vault config file
            #apk add gettext libintl
            envsubst < .circleci/vault/agent.hcl.tpl > .circleci/vault/agent.hcl
            # This config indicates which secrets to collect and how to authenticate     
            vault agent -config=.circleci/vault/agent.hcl
            source .
      - run:
          name: Set Environment Variables from Vault
          command: |
            # In order to properly expose values in Environment, we _source_ the shell values written by agent
            source .circleci/vault/setenv

jobs:
  setup-vault-and-load-secrets:
    docker: 
      - image: cimg/base:2023:1
    steps:
      - checkout
      - install-vault
      - vault-auto-auth
      - echo

  use-secrets:
    docker: 
      - image: cimg/base:2023:1
    steps:
      - run: echo "Username is $SECRET_DEMO_USERNAME, password is $SECRET_DEMO_PASSWORD"

workflows:
  vault: 
    jobs:
      - setup-vault-and-load-secrets:
          context:
            - circleci-vault-demo
      - use-secrets:
          requires:
            - setup-vault-and-load-secrets

# VS Code Extension Version: 1.5.1